# wob — Wayland Overlay Bar
# Catppuccin Macchiato: bg=#24273a border/bar=#8aadf4 overflow=#ed8796

timeout = 1000
max = 100

width = 400
height = 40
border_size = 3
padding = 8

anchor = bottom center
margin = 80

background_color = 24273ae6
border_color = 8aadf4ff
bar_color = 8aadf4ff

overflow_background_color = ed8796e6
overflow_border_color = ed8796ff
overflow_bar_color = ed8796ff
