# ============================================================
# Kitty Config
# Catppuccin Macchiato Theme
# ============================================================

font_family JetBrains Mono
bold_font auto
italic_font auto
bold_italic_font auto

font_size 11.5

include macchiato.conf

background_opacity 0.85
dynamic_background_opacity yes

window_padding_width 8
confirm_os_window_close 0

# Paste on Right Click
mouse_map right press ungrabbed paste_from_clipboard

shell_integration disabled

enable_audio_bell no
